# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[workspace-to-monitor-force-assignment]
11 = 'secondary'
12 = 'secondary'
13 = 'secondary'
14 = 'secondary'
15 = 'secondary'
16 = 'secondary'
17 = 'secondary'
18 = 'secondary'
19 = 'secondary'
20 = 'secondary'

[mode.main.binding]
alt-enter = 'exec-and-forget open -n ~/Applications/.app'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-g = 'split horizontal'
alt-v = 'split vertical'

alt-f = 'fullscreen'

alt-a = 'layout v_accordion'               # 'layout stacking' in i3
alt-s = 'layout h_accordion'               # 'layout tabbed' in i3
alt-d = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-q = 'workspace 1'
alt-w = 'workspace 2'
alt-e = 'workspace 3'
alt-r = 'workspace 4'
alt-t = 'workspace 5'
alt-y = 'workspace 6'
alt-u = 'workspace 7'
alt-i = 'workspace 8'
alt-o = 'workspace 9'
alt-p = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-q = 'move-node-to-workspace 1'
alt-shift-w = 'move-node-to-workspace 2'
alt-shift-e = 'move-node-to-workspace 3'
alt-shift-r = 'move-node-to-workspace 4'
alt-shift-t = 'move-node-to-workspace 5'
alt-shift-y = 'move-node-to-workspace 6'
alt-shift-u = 'move-node-to-workspace 7'
alt-shift-i = 'move-node-to-workspace 8'
alt-shift-o = 'move-node-to-workspace 9'
alt-shift-p = 'move-node-to-workspace 10'

alt-ctrl-1 = 'workspace 11'
alt-ctrl-2 = 'workspace 12'
alt-ctrl-3 = 'workspace 13'
alt-ctrl-4 = 'workspace 14'
alt-ctrl-5 = 'workspace 15'
alt-ctrl-6 = 'workspace 16'
alt-ctrl-7 = 'workspace 17'
alt-ctrl-8 = 'workspace 18'
alt-ctrl-9 = 'workspace 19'
alt-ctrl-0 = 'workspace 20'

alt-ctrl-shift-1 = 'move-node-to-workspace 11'
alt-ctrl-shift-2 = 'move-node-to-workspace 12'
alt-ctrl-shift-3 = 'move-node-to-workspace 13'
alt-ctrl-shift-4 = 'move-node-to-workspace 14'
alt-ctrl-shift-5 = 'move-node-to-workspace 15'
alt-ctrl-shift-6 = 'move-node-to-workspace 16'
alt-ctrl-shift-7 = 'move-node-to-workspace 17'
alt-ctrl-shift-8 = 'move-node-to-workspace 18'
alt-ctrl-shift-9 = 'move-node-to-workspace 19'
alt-ctrl-shift-0 = 'move-node-to-workspace 20'

alt-ctrl-q = 'workspace 11'
alt-ctrl-w = 'workspace 12'
alt-ctrl-e = 'workspace 13'
alt-ctrl-r = 'workspace 14'
alt-ctrl-t = 'workspace 15'
alt-ctrl-y = 'workspace 16'
alt-ctrl-u = 'workspace 17'
alt-ctrl-i = 'workspace 18'
alt-ctrl-o = 'workspace 19'
alt-ctrl-p = 'workspace 20'

alt-ctrl-shift-q = 'move-node-to-workspace 11'
alt-ctrl-shift-w = 'move-node-to-workspace 12'
alt-ctrl-shift-e = 'move-node-to-workspace 13'
alt-ctrl-shift-r = 'move-node-to-workspace 14'
alt-ctrl-shift-t = 'move-node-to-workspace 15'
alt-ctrl-shift-y = 'move-node-to-workspace 16'
alt-ctrl-shift-u = 'move-node-to-workspace 17'
alt-ctrl-shift-i = 'move-node-to-workspace 18'
alt-ctrl-shift-o = 'move-node-to-workspace 19'
alt-ctrl-shift-p = 'move-node-to-workspace 20'

alt-shift-c = 'reload-config'

# alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
