name: Main workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Make
        run: make
